
import type { Metadata } from 'next';
import PostList from '../component/posts/PostList';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div>
     
      {children}
    </div>
  );
}