
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/component/navbar";
import TimerComponent from "./component/timerComponent";
import SessionWrapper from "@/app/component/SessionProvider"
import { getServerSession } from "next-auth"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"

import PostList from "./component/posts/PostList";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" dir="rtl">
      <body>
     


   <SessionWrapper session={session}>
   <TimerComponent></TimerComponent>
      <Navbar></Navbar>
      {children}
      
       
        </SessionWrapper> 
      </body>
    </html>
  );
}

