
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./component/navbar";
import TimerComponent from "./component/timerComponent";
import PostList from "./component/posts/PostList";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (

    <html lang="en" dir="rtl">
      <body>
        <Navbar></Navbar>
        <TimerComponent></TimerComponent>
        <PostList/>
        {children}
      </body>
    </html>
  );
}

