import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/component/navbar";
import TimerComponent from "./component/timerComponent";
import SessionWrapper from "@/app/component/SessionProvider"
import { getServerSession } from "next-auth"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import PostList from "./component/posts/PostList";
import useNavbarStore from "./store/navbarStore";
import ClientSideLayout from "./component/users/ClientSideLayout";
import Footer from "./component/Footer";
import Script from "next/script";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions)


  return (
    <html lang="en" dir="rtl">
      <body className="flex flex-col h-screen overflow-hidden">
        <SessionWrapper session={session}>
          <Navbar />
          <TimerComponent></TimerComponent>
          <div className="flex flex-1 overflow-hidden">
            {/* תפריט צד ימני */}
            <ClientSideLayout />
            {/* תוכן ראשי */}
            <main className="flex-1 bg-gray-50 overflow-y-auto p-4 pt-[120px]">
              {children}
            </main>
          </div>
          <Footer />

        </SessionWrapper>
        <Script
          src="https://cdn.enable.co.il/licenses/enable-L35466r8t1ik9ew4-1224-66980/init.js"
          strategy="afterInteractive"
        >
        </Script>
      </body>
    </html>
  );
}

