
import ConsumerSidebar from '@/app/component/users/userSidebar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <div>
      <ConsumerSidebar></ConsumerSidebar>
      {children}
    </div>
  );
}
